name: CI/CD for Ddareungi Producer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Archive production artifacts
      run: |
        mkdir -p artifact
        zip -r artifact/app.zip .
      continue-on-error: false

    - name: Upload production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: artifact/app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: app
        path: artifact

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli

    - name: Deploy to AWS CodeDeploy
      run: |
        aws deploy push \
          --application-name producer-Application \
          --s3-location s3://ddareungi-kafka-deploy-bucket/producer.zip \
          --ignore-hidden-files
        aws deploy create-deployment \
          --application-name producer-Application \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name MyDeploymentGroup \
          --s3-location bucket=ddareungi-kafka-deploy-bucket,key=producer.zip,bundleType=zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2

